# vim:ft=kitty

## name:     omarchy lupine
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/lupine.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #000000
background              #fafafa
selection_foreground    #fafafa
selection_background    #f930fb

# Cursor colors
cursor                  #f930fb
cursor_text_color       #fafafa

# Scrollbar colors
scrollbar_handle_color  #212121
scrollbar_track_color   #c8c8c8

# URL color when hovering with mouse
url_color               #f930fb

# Kitty window border colors
active_border_color     #5482ff
inactive_border_color   #a4a4a4
bell_border_color       #026fde

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #dedede
active_tab_background   #8a4ad7
inactive_tab_foreground #000000
inactive_tab_background #ececec
tab_bar_background      #dedede

# Colors for marks (marked text in the terminal)
mark1_foreground #fafafa
mark1_background #5482ff
mark2_foreground #fafafa
mark2_background #8a4ad7
mark3_foreground #fafafa
mark3_background #1b66e3

# The 16 terminal colors

# black
color0 #c8c8c8
color8 #f5f5f5

# red
color1 #c900c4
color9 #c900c4

# green
color2  #4a2fd0
color10 #4a2fd0

# yellow
color3  #026fde
color11 #026fde

# blue
color4  #3264eb
color12 #3264eb

# magenta
color5  #b363ff
color13 #b363ff

# cyan
color6  #0c67de
color14 #0c67de

# white
color7  #424242
color15 #212121
