# vim:ft=kitty

## name:     Jujutsu Kaisen
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/jujutsu-kaisen.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f7efff
background              #160f1b
selection_foreground    #160f1b
selection_background    #e9c8ff

# Cursor colors
cursor                  #e9c8ff
cursor_text_color       #160f1b

# Scrollbar colors
scrollbar_handle_color  #92809a
scrollbar_track_color   #261b2d

# URL color when hovering with mouse
url_color               #e9c8ff

# Kitty window border colors
active_border_color     #c3a7ff
inactive_border_color   #4a394f
bell_border_color       #f2d66b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #09060c
active_tab_background   #b06cff
inactive_tab_foreground #f7efff
inactive_tab_background #100a14
tab_bar_background      #09060c

# Colors for marks (marked text in the terminal)
mark1_foreground #160f1b
mark1_background #c3a7ff
mark2_foreground #160f1b
mark2_background #b06cff
mark3_foreground #160f1b
mark3_background #7899ff

# The 16 terminal colors

# black
color0 #261b2d
color8 #33253b

# red
color1 #ff5c7a
color9 #ff5c7a

# green
color2  #6ed6a5
color10 #6ed6a5

# yellow
color3  #f2d66b
color11 #f2d66b

# blue
color4  #5b7cff
color12 #5b7cff

# magenta
color5  #ff6b9d
color13 #ff6b9d

# cyan
color6  #63c7c2
color14 #63c7c2

# white
color7  #d5c4dd
color15 #b3a1ba
