THEME_NAME="Jujutsu Kaisen"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="mauve"
BORDER_INACTIVE="red"
GENERATOR="custom"
KITTY_NAME="Jujutsu Kaisen"
KITTY_UPSTREAM="jujutsu-kaisen"
HYPR_HEADER="Jujutsu Kaisen"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
