# vim:ft=kitty

## name:     omarchy nord
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/nord.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #d8dee9
background              #2e3440
selection_foreground    #2e3440
selection_background    #bf616a

# Cursor colors
cursor                  #bf616a
cursor_text_color       #2e3440

# Scrollbar colors
scrollbar_handle_color  #d8dee9
scrollbar_track_color   #4a5262

# URL color when hovering with mouse
url_color               #bf616a

# Kitty window border colors
active_border_color     #81a1c1
inactive_border_color   #525b6a
bell_border_color       #ebcb8b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #191c23
active_tab_background   #b48ead
inactive_tab_foreground #d8dee9
inactive_tab_background #222730
tab_bar_background      #191c23

# Colors for marks (marked text in the terminal)
mark1_foreground #2e3440
mark1_background #81a1c1
mark2_foreground #2e3440
mark2_background #b48ead
mark3_foreground #2e3440
mark3_background #85b4ca

# The 16 terminal colors

# black
color0 #4a5262
color8 #3b4252

# red
color1 #bf616a
color9 #bf616a

# green
color2  #a3be8c
color10 #a3be8c

# yellow
color3  #ebcb8b
color11 #ebcb8b

# blue
color4  #81a1c1
color12 #81a1c1

# magenta
color5  #b48ead
color13 #b48ead

# cyan
color6  #88c0d0
color14 #88c0d0

# white
color7  #adb5c4
color15 #d8dee9
