# vim:ft=kitty

## name:     NieR: Automata
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/nier-automata.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f2f0eb
background              #1b1a19
selection_foreground    #1b1a19
selection_background    #f2eee7

# Cursor colors
cursor                  #f2eee7
cursor_text_color       #1b1a19

# Scrollbar colors
scrollbar_handle_color  #918f8a
scrollbar_track_color   #2d2c2a

# URL color when hovering with mouse
url_color               #f2eee7

# Kitty window border colors
active_border_color     #d4d0ca
inactive_border_color   #555451
bell_border_color       #c6b98d

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0b0b0a
active_tab_background   #a9a29a
inactive_tab_foreground #f2f0eb
inactive_tab_background #131312
tab_bar_background      #0b0b0a

# Colors for marks (marked text in the terminal)
mark1_foreground #1b1a19
mark1_background #d4d0ca
mark2_foreground #1b1a19
mark2_background #a9a29a
mark3_foreground #1b1a19
mark3_background #929d99

# The 16 terminal colors

# black
color0 #2d2c2a
color8 #3b3a37

# red
color1 #9b8f84
color9 #9b8f84

# green
color2  #8c9b80
color10 #8c9b80

# yellow
color3  #c6b98d
color11 #c6b98d

# blue
color4  #777f7c
color12 #777f7c

# magenta
color5  #d8b8ae
color13 #d8b8ae

# cyan
color6  #8da29d
color14 #8da29d

# white
color7  #d1cfca
color15 #b3b1ac
