# vim:ft=kitty

## name:     Lofi City
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/lofi-city.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e5edf4
background              #191d23
selection_foreground    #191d23
selection_background    #d5e5f2

# Cursor colors
cursor                  #d5e5f2
cursor_text_color       #191d23

# Scrollbar colors
scrollbar_handle_color  #8693a2
scrollbar_track_color   #272d34

# URL color when hovering with mouse
url_color               #d5e5f2

# Kitty window border colors
active_border_color     #b4b3d1
inactive_border_color   #4b5563
bell_border_color       #d7c58f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0a0d10
active_tab_background   #8b85b7
inactive_tab_foreground #e5edf4
inactive_tab_background #12161b
tab_bar_background      #0a0d10

# Colors for marks (marked text in the terminal)
mark1_foreground #191d23
mark1_background #b4b3d1
mark2_foreground #191d23
mark2_background #8b85b7
mark3_foreground #191d23
mark3_background #6485b5

# The 16 terminal colors

# black
color0 #272d34
color8 #303740

# red
color1 #ae6d86
color9 #ae6d86

# green
color2  #8eafa4
color10 #8eafa4

# yellow
color3  #d7c58f
color11 #d7c58f

# blue
color4  #445f92
color12 #445f92

# magenta
color5  #c99bbd
color13 #c99bbd

# cyan
color6  #78a6b2
color14 #78a6b2

# white
color7  #c6d2de
color15 #a7b3c1
