THEME_NAME="Lofi City"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="mauve"
BORDER_INACTIVE="sky"
GENERATOR="custom"
KITTY_NAME="Lofi City"
KITTY_UPSTREAM="lofi-city"
HYPR_HEADER="Lofi City"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
