# vim:ft=kitty

## name:     omarchy kanagawa
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/kanagawa.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #e82424

# Cursor colors
cursor                  #e82424
cursor_text_color       #1f1f28

# Scrollbar colors
scrollbar_handle_color  #dcd7ba
scrollbar_track_color   #3e4854

# URL color when hovering with mouse
url_color               #e82424

# Kitty window border colors
active_border_color     #7fb4ca
inactive_border_color   #555452
bell_border_color       #c0a36e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #111116
active_tab_background   #957fb8
inactive_tab_foreground #dcd7ba
inactive_tab_background #17171e
tab_bar_background      #111116

# Colors for marks (marked text in the terminal)
mark1_foreground #1f1f28
mark1_background #7fb4ca
mark2_foreground #1f1f28
mark2_background #957fb8
mark3_foreground #1f1f28
mark3_background #7298a9

# The 16 terminal colors

# black
color0 #3e4854
color8 #223249

# red
color1 #c34043
color9 #c34043

# green
color2  #76946a
color10 #76946a

# yellow
color3  #c0a36e
color11 #c0a36e

# blue
color4  #7e9cd8
color12 #7e9cd8

# magenta
color5  #938aa9
color13 #938aa9

# cyan
color6  #6a9589
color14 #6a9589

# white
color7  #c8c093
color15 #dcd7ba
