# vim:ft=kitty

## name:     omarchy osaka-jade
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/osaka-jade.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f7e8b2
background              #111c18
selection_foreground    #111c18
selection_background    #db9f9c

# Cursor colors
cursor                  #db9f9c
cursor_text_color       #111c18

# Scrollbar colors
scrollbar_handle_color  #c1c497
scrollbar_track_color   #446457

# URL color when hovering with mouse
url_color               #db9f9c

# Kitty window border colors
active_border_color     #acd4cf
inactive_border_color   #5a8176
bell_border_color       #459451

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #090f0d
active_tab_background   #d2689c
inactive_tab_foreground #f7e8b2
inactive_tab_background #0c1512
tab_bar_background      #090f0d

# Colors for marks (marked text in the terminal)
mark1_foreground #111c18
mark1_background #acd4cf
mark2_foreground #111c18
mark2_background #d2689c
mark3_foreground #111c18
mark3_background #3bbb9d

# The 16 terminal colors

# black
color0 #446457
color8 #23372b

# red
color1 #ff5345
color9 #ff5345

# green
color2  #549e6a
color10 #549e6a

# yellow
color3  #459451
color11 #459451

# blue
color4  #509475
color12 #509475

# magenta
color5  #75bbb3
color13 #75bbb3

# cyan
color6  #2dd5b7
color14 #2dd5b7

# white
color7  #d6d5bc
color15 #c1c497
