# vim:ft=kitty

## name:     omarchy rose-pine
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/rose-pine.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #575279
background              #faf4ed
selection_foreground    #faf4ed
selection_background    #b4637a

# Cursor colors
cursor                  #b4637a
cursor_text_color       #faf4ed

# Scrollbar colors
scrollbar_handle_color  #575279
scrollbar_track_color   #d2cbcc

# URL color when hovering with mouse
url_color               #b4637a

# Kitty window border colors
active_border_color     #56949f
inactive_border_color   #bab5be
bell_border_color       #ea9d34

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #e1dbd5
active_tab_background   #907aa9
inactive_tab_foreground #575279
inactive_tab_background #ede7e1
tab_bar_background      #e1dbd5

# Colors for marks (marked text in the terminal)
mark1_foreground #faf4ed
mark1_background #56949f
mark2_foreground #faf4ed
mark2_background #907aa9
mark3_foreground #faf4ed
mark3_background #a3898b

# The 16 terminal colors

# black
color0 #d2cbcc
color8 #f2e9e1

# red
color1 #b4637a
color9 #b4637a

# green
color2  #286983
color10 #286983

# yellow
color3  #ea9d34
color11 #ea9d34

# blue
color4  #56949f
color12 #56949f

# magenta
color5  #907aa9
color13 #907aa9

# cyan
color6  #d7827e
color14 #d7827e

# white
color7  #6e6a86
color15 #575279
