# vim:ft=kitty

## name:     Elden Ring
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/elden-ring.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e8e0c8
background              #151714
selection_foreground    #151714
selection_background    #d8d1b5

# Cursor colors
cursor                  #d8d1b5
cursor_text_color       #151714

# Scrollbar colors
scrollbar_handle_color  #827c6b
scrollbar_track_color   #252722

# URL color when hovering with mouse
url_color               #d8d1b5

# Kitty window border colors
active_border_color     #a7a69c
inactive_border_color   #44423b
bell_border_color       #d2ad45

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #080908
active_tab_background   #82735b
inactive_tab_foreground #e8e0c8
inactive_tab_background #10110f
tab_bar_background      #080908

# Colors for marks (marked text in the terminal)
mark1_foreground #151714
mark1_background #a7a69c
mark2_foreground #151714
mark2_background #82735b
mark3_foreground #151714
mark3_background #607f8c

# The 16 terminal colors

# black
color0 #252722
color8 #2e3029

# red
color1 #9d4a37
color9 #9d4a37

# green
color2  #6b8754
color10 #6b8754

# yellow
color3  #d2ad45
color11 #d2ad45

# blue
color4  #3d6472
color12 #3d6472

# magenta
color5  #a88f61
color13 #a88f61

# cyan
color6  #4f8b79
color14 #4f8b79

# white
color7  #c8bea2
color15 #a69d86
