THEME_NAME="Elden Ring"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="yellow"
BORDER_INACTIVE="green"
GENERATOR="custom"
KITTY_NAME="Elden Ring"
KITTY_UPSTREAM="elden-ring"
HYPR_HEADER="Elden Ring"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
