# vim:ft=kitty

## name:     omarchy miasma
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/miasma.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #c2c2b0
background              #222222
selection_foreground    #222222
selection_background    #685742

# Cursor colors
cursor                  #685742
cursor_text_color       #222222

# Scrollbar colors
scrollbar_handle_color  #c2c2b0
scrollbar_track_color   #3a3a3a

# URL color when hovering with mouse
url_color               #685742

# Kitty window border colors
active_border_color     #78824b
inactive_border_color   #434343
bell_border_color       #b36d43

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #121212
active_tab_background   #bb7744
inactive_tab_foreground #c2c2b0
inactive_tab_background #191919
tab_bar_background      #121212

# Colors for marks (marked text in the terminal)
mark1_foreground #222222
mark1_background #78824b
mark2_foreground #222222
mark2_background #bb7744
mark3_foreground #222222
mark3_background #a99750

# The 16 terminal colors

# black
color0 #3a3a3a
color8 #2c2c2c

# red
color1 #685742
color9 #685742

# green
color2  #5f875f
color10 #5f875f

# yellow
color3  #b36d43
color11 #b36d43

# blue
color4  #78824b
color12 #78824b

# magenta
color5  #bb7744
color13 #bb7744

# cyan
color6  #c9a554
color14 #c9a554

# white
color7  #8a8a7e
color15 #c2c2b0
