# vim:ft=kitty

## name:     One Piece
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/one-piece.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f3fbff
background              #122127
selection_foreground    #122127
selection_background    #d8f1ff

# Cursor colors
cursor                  #d8f1ff
cursor_text_color       #122127

# Scrollbar colors
scrollbar_handle_color  #8299a3
scrollbar_track_color   #22353d

# URL color when hovering with mouse
url_color               #d8f1ff

# Kitty window border colors
active_border_color     #9fb7ff
inactive_border_color   #46575e
bell_border_color       #ffd166

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #071115
active_tab_background   #7c83ff
inactive_tab_foreground #f3fbff
inactive_tab_background #0d191e
tab_bar_background      #071115

# Colors for marks (marked text in the terminal)
mark1_foreground #122127
mark1_background #9fb7ff
mark2_foreground #122127
mark2_background #7c83ff
mark3_foreground #122127
mark3_background #438de0

# The 16 terminal colors

# black
color0 #22353d
color8 #2e454e

# red
color1 #ef476f
color9 #ef476f

# green
color2  #35c98b
color10 #35c98b

# yellow
color3  #ffd166
color11 #ffd166

# blue
color4  #1768ac
color12 #1768ac

# magenta
color5  #ff7091
color13 #ff7091

# cyan
color6  #3ec6c9
color14 #3ec6c9

# white
color7  #cde3ec
color15 #a8c0ca
