THEME_NAME="One Piece"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="blue"
BORDER_INACTIVE="peach"
GENERATOR="custom"
KITTY_NAME="One Piece"
KITTY_UPSTREAM="one-piece"
HYPR_HEADER="One Piece"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
