# vim:ft=kitty

## name:     omarchy lumon
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/lumon.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #f2fcff
background              #16242d
selection_foreground    #16242d
selection_background    #73a6cb

# Cursor colors
cursor                  #73a6cb
cursor_text_color       #16242d

# Scrollbar colors
scrollbar_handle_color  #d6e2ee
scrollbar_track_color   #2c4c67

# URL color when hovering with mouse
url_color               #73a6cb

# Kitty window border colors
active_border_color     #f2fcff
inactive_border_color   #3a6482
bell_border_color       #6fa4c9

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0b1216
active_tab_background   #8bc9eb
inactive_tab_foreground #f2fcff
inactive_tab_background #101b21
tab_bar_background      #0b1216

# Colors for marks (marked text in the terminal)
mark1_foreground #16242d
mark1_background #f2fcff
mark2_foreground #16242d
mark2_background #8bc9eb
mark3_foreground #16242d
mark3_background #98d2ee

# The 16 terminal colors

# black
color0 #2c4c67
color8 #1b2d40

# red
color1 #4d86b0
color9 #4d86b0

# green
color2  #5e95bc
color10 #5e95bc

# yellow
color3  #6fa4c9
color11 #6fa4c9

# blue
color4  #6fb8e3
color12 #6fb8e3

# magenta
color5  #b1d8ee
color13 #b1d8ee

# cyan
color6  #b4e4f6
color14 #b4e4f6

# white
color7  #d6e2ee
color15 #d6e2ee
