# vim:ft=kitty

## name:     omarchy last-horizon
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/last-horizon.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e2dddc
background              #0c0b0c
selection_foreground    #0c0b0c
selection_background    #c38b7b

# Cursor colors
cursor                  #c38b7b
cursor_text_color       #0c0b0c

# Scrollbar colors
scrollbar_handle_color  #fafcfb
scrollbar_track_color   #272224

# URL color when hovering with mouse
url_color               #c38b7b

# Kitty window border colors
active_border_color     #b59790
inactive_border_color   #3d3739
bell_border_color       #6b5e73

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #060606
active_tab_background   #c4d8e2
inactive_tab_foreground #e2dddc
inactive_tab_background #090809
tab_bar_background      #060606

# Colors for marks (marked text in the terminal)
mark1_foreground #0c0b0c
mark1_background #b59790
mark2_foreground #0c0b0c
mark2_background #c4d8e2
mark3_foreground #0c0b0c
mark3_background #ab9ca7

# The 16 terminal colors

# black
color0 #272224
color8 #0c0b0c

# red
color1 #c38b7b
color9 #c38b7b

# green
color2  #87a9b0
color10 #87a9b0

# yellow
color3  #6b5e73
color11 #6b5e73

# blue
color4  #b59790
color12 #b59790

# magenta
color5  #c4d8e2
color13 #c4d8e2

# cyan
color6  #a5a0b6
color14 #a5a0b6

# white
color7  #cfd3cd
color15 #fafcfb
