# vim:ft=kitty

## name:     Your Name
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/your-name.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #fff7f2
background              #1c1720
selection_foreground    #1c1720
selection_background    #ffd8e6

# Cursor colors
cursor                  #ffd8e6
cursor_text_color       #1c1720

# Scrollbar colors
scrollbar_handle_color  #9d94a3
scrollbar_track_color   #2e2632

# URL color when hovering with mouse
url_color               #ffd8e6

# Kitty window border colors
active_border_color     #a8a2e5
inactive_border_color   #514a58
bell_border_color       #ffd98c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0d0a10
active_tab_background   #a681dd
inactive_tab_foreground #fff7f2
inactive_tab_background #151119
tab_bar_background      #0d0a10

# Colors for marks (marked text in the terminal)
mark1_foreground #1c1720
mark1_background #a8a2e5
mark2_foreground #1c1720
mark2_background #a681dd
mark3_foreground #1c1720
mark3_background #6989e5

# The 16 terminal colors

# black
color0 #2e2632
color8 #3a303d

# red
color1 #df627d
color9 #df627d

# green
color2  #83d6a6
color10 #83d6a6

# yellow
color3  #ffd98c
color11 #ffd98c

# blue
color4  #5261b8
color12 #5261b8

# magenta
color5  #f77fa8
color13 #f77fa8

# cyan
color6  #76c7cf
color14 #76c7cf

# white
color7  #e8d9df
color15 #c5b8c5
