THEME_NAME="Your Name"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="blue"
BORDER_INACTIVE="pink"
GENERATOR="custom"
KITTY_NAME="Your Name"
KITTY_UPSTREAM="your-name"
HYPR_HEADER="Your Name"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
