# vim:ft=kitty

## name:     Nisekoi
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/nisekoi.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #edf6ff
background              #151a23
selection_foreground    #151a23
selection_background    #e0efff

# Cursor colors
cursor                  #e0efff
cursor_text_color       #151a23

# Scrollbar colors
scrollbar_handle_color  #8997ae
scrollbar_track_color   #242b39

# URL color when hovering with mouse
url_color               #e0efff

# Kitty window border colors
active_border_color     #a8a6e5
inactive_border_color   #48556a
bell_border_color       #ead46d

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #080b10
active_tab_background   #9d76df
inactive_tab_foreground #edf6ff
inactive_tab_background #0f131a
tab_bar_background      #080b10

# Colors for marks (marked text in the terminal)
mark1_foreground #151a23
mark1_background #a8a6e5
mark2_foreground #151a23
mark2_background #9d76df
mark3_foreground #151a23
mark3_background #5e7fdc

# The 16 terminal colors

# black
color0 #242b39
color8 #2d3545

# red
color1 #e95879
color9 #e95879

# green
color2  #70b995
color10 #70b995

# yellow
color3  #ead46d
color11 #ead46d

# blue
color4  #3453b8
color12 #3453b8

# magenta
color5  #f36b9e
color13 #f36b9e

# cyan
color6  #5caab1
color14 #5caab1

# white
color7  #cdd9e8
color15 #aebbd0
