THEME_NAME="Nisekoi"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="pink"
BORDER_INACTIVE="blue"
GENERATOR="custom"
KITTY_NAME="Nisekoi"
KITTY_UPSTREAM="nisekoi"
HYPR_HEADER="Nisekoi"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
