# vim:ft=kitty

## name:     Akira
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/akira.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #fff1ed
background              #191218
selection_foreground    #191218
selection_background    #ffd6d6

# Cursor colors
cursor                  #ffd6d6
cursor_text_color       #191218

# Scrollbar colors
scrollbar_handle_color  #9c818e
scrollbar_track_color   #2a1f29

# URL color when hovering with mouse
url_color               #ffd6d6

# Kitty window border colors
active_border_color     #b09aff
inactive_border_color   #53434f
bell_border_color       #ffd166

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0a070b
active_tab_background   #b44dff
inactive_tab_foreground #fff1ed
inactive_tab_background #120c12
tab_bar_background      #0a070b

# Colors for marks (marked text in the terminal)
mark1_foreground #191218
mark1_background #b09aff
mark2_foreground #191218
mark2_background #b44dff
mark3_foreground #191218
mark3_background #4574e8

# The 16 terminal colors

# black
color0 #2a1f29
color8 #352936

# red
color1 #f43b52
color9 #f43b52

# green
color2  #64d6a4
color10 #64d6a4

# yellow
color3  #ffd166
color11 #ffd166

# blue
color4  #1450bb
color12 #1450bb

# magenta
color5  #ff5577
color13 #ff5577

# cyan
color6  #52c7d1
color14 #52c7d1

# white
color7  #e3c8ca
color15 #c0a4ae
