THEME_NAME="Akira"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="red"
BORDER_INACTIVE="blue"
GENERATOR="custom"
KITTY_NAME="Akira"
KITTY_UPSTREAM="akira"
HYPR_HEADER="Akira"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
