# vim:ft=kitty

## name:     Evangelion
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/evangelion.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #eefaff
background              #17161b
selection_foreground    #17161b
selection_background    #e1f6ff

# Cursor colors
cursor                  #e1f6ff
cursor_text_color       #17161b

# Scrollbar colors
scrollbar_handle_color  #7e8b95
scrollbar_track_color   #26232d

# URL color when hovering with mouse
url_color               #e1f6ff

# Kitty window border colors
active_border_color     #a59cff
inactive_border_color   #454f58
bell_border_color       #f8dc70

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0a090c
active_tab_background   #9b51e0
inactive_tab_foreground #eefaff
inactive_tab_background #111015
tab_bar_background      #0a090c

# Colors for marks (marked text in the terminal)
mark1_foreground #17161b
mark1_background #a59cff
mark2_foreground #17161b
mark2_background #9b51e0
mark3_foreground #17161b
mark3_background #4e73f0

# The 16 terminal colors

# black
color0 #26232d
color8 #302c38

# red
color1 #f0446c
color9 #f0446c

# green
color2  #6ed0b7
color10 #6ed0b7

# yellow
color3  #f8dc70
color11 #f8dc70

# blue
color4  #1647b8
color12 #1647b8

# magenta
color5  #ff3b7b
color13 #ff3b7b

# cyan
color6  #62c4d6
color14 #62c4d6

# white
color7  #c6d4df
color15 #a1adb8
