THEME_NAME="Evangelion"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="red"
BORDER_INACTIVE="blue"
GENERATOR="custom"
KITTY_NAME="Evangelion"
KITTY_UPSTREAM="evangelion"
HYPR_HEADER="Evangelion"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
