# vim:ft=kitty

## name:     Urban Ruins
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/urban-ruins.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e7ece9
background              #181b1b
selection_foreground    #181b1b
selection_background    #d8e2df

# Cursor colors
cursor                  #d8e2df
cursor_text_color       #181b1b

# Scrollbar colors
scrollbar_handle_color  #828d89
scrollbar_track_color   #272c2b

# URL color when hovering with mouse
url_color               #d8e2df

# Kitty window border colors
active_border_color     #b4bac0
inactive_border_color   #474f4d
bell_border_color       #c8b76c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #090b0b
active_tab_background   #9c9ca8
inactive_tab_foreground #e7ece9
inactive_tab_background #111313
tab_bar_background      #090b0b

# Colors for marks (marked text in the terminal)
mark1_foreground #181b1b
mark1_background #b4bac0
mark2_foreground #181b1b
mark2_background #9c9ca8
mark3_foreground #181b1b
mark3_background #688794

# The 16 terminal colors

# black
color0 #272c2b
color8 #303634

# red
color1 #b45b52
color9 #b45b52

# green
color2  #789b75
color10 #789b75

# yellow
color3  #c8b76c
color11 #c8b76c

# blue
color4  #456777
color12 #456777

# magenta
color5  #c6a5a0
color13 #c6a5a0

# cyan
color6  #6d9991
color14 #6d9991

# white
color7  #c5ceca
color15 #a4afab
