THEME_NAME="Urban Ruins"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="peach"
BORDER_INACTIVE="teal"
GENERATOR="custom"
KITTY_NAME="Urban Ruins"
KITTY_UPSTREAM="urban-ruins"
HYPR_HEADER="Urban Ruins"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
