# vim:ft=kitty

## name:     omarchy matte-black
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/matte-black.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #bebebe
background              #121212
selection_foreground    #121212
selection_background    #b91c1c

# Cursor colors
cursor                  #b91c1c
cursor_text_color       #121212

# Scrollbar colors
scrollbar_handle_color  #bebebe
scrollbar_track_color   #313131

# URL color when hovering with mouse
url_color               #b91c1c

# Kitty window border colors
active_border_color     #f59e0b
inactive_border_color   #3e3e3e
bell_border_color       #b91c1c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #090909
active_tab_background   #d35f5f
inactive_tab_foreground #bebebe
inactive_tab_background #0d0d0d
tab_bar_background      #090909

# Colors for marks (marked text in the terminal)
mark1_foreground #121212
mark1_background #f59e0b
mark2_foreground #121212
mark2_background #d35f5f
mark3_foreground #121212
mark3_background #ceab77

# The 16 terminal colors

# black
color0 #313131
color8 #1e1e1e

# red
color1 #d35f5f
color9 #d35f5f

# green
color2  #ffc107
color10 #ffc107

# yellow
color3  #b91c1c
color11 #b91c1c

# blue
color4  #e68e0d
color12 #e68e0d

# magenta
color5  #b91c1c
color13 #b91c1c

# cyan
color6  #bebebe
color14 #bebebe

# white
color7  #8a8a8d
color15 #bebebe
