# vim:ft=kitty

## name:     Cyberpunk Neon
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/cyberpunk-neon.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e9fbff
background              #121a21
selection_foreground    #121a21
selection_background    #dffaff

# Cursor colors
cursor                  #dffaff
cursor_text_color       #121a21

# Scrollbar colors
scrollbar_handle_color  #7d91a0
scrollbar_track_color   #202c36

# URL color when hovering with mouse
url_color               #dffaff

# Kitty window border colors
active_border_color     #8da7ff
inactive_border_color   #435460
bell_border_color       #f9e05f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #070b0e
active_tab_background   #a66cff
inactive_tab_foreground #e9fbff
inactive_tab_background #0c1318
tab_bar_background      #070b0e

# Colors for marks (marked text in the terminal)
mark1_foreground #121a21
mark1_background #8da7ff
mark2_foreground #121a21
mark2_background #a66cff
mark3_foreground #121a21
mark3_background #3e7bff

# The 16 terminal colors

# black
color0 #202c36
color8 #2b3743

# red
color1 #ff365f
color9 #ff365f

# green
color2  #4de2b2
color10 #4de2b2

# yellow
color3  #f9e05f
color11 #f9e05f

# blue
color4  #1846c7
color12 #1846c7

# magenta
color5  #ff4fa3
color13 #ff4fa3

# cyan
color6  #35d5e8
color14 #35d5e8

# white
color7  #bfd6df
color15 #9fb4c1
