THEME_NAME="Cyberpunk Neon"
THEME_MODE="dark"
QT_SCHEME=""
BORDER_ACCENT="pink"
BORDER_INACTIVE="teal"
GENERATOR="custom"
KITTY_NAME="Cyberpunk Neon"
KITTY_UPSTREAM="cyberpunk-neon"
HYPR_HEADER="Cyberpunk Neon"
ACTIVE_ALPHA="cc"
INACTIVE_ALPHA="99"
