# vim:ft=kitty

## name:     omarchy hackerman
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/hackerman.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #ddf7ff
background              #0b0c16
selection_foreground    #0b0c16
selection_background    #85ff9d

# Cursor colors
cursor                  #85ff9d
cursor_text_color       #0b0c16

# Scrollbar colors
scrollbar_handle_color  #ddf7ff
scrollbar_track_color   #33364e

# URL color when hovering with mouse
url_color               #85ff9d

# Kitty window border colors
active_border_color     #c4d2ed
inactive_border_color   #494c69
bell_border_color       #50f7d4

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #06060c
active_tab_background   #86a7df
inactive_tab_foreground #ddf7ff
inactive_tab_background #080910
tab_bar_background      #06060c

# Colors for marks (marked text in the terminal)
mark1_foreground #0b0c16
mark1_background #c4d2ed
mark2_foreground #0b0c16
mark2_background #86a7df
mark3_foreground #0b0c16
mark3_background #7ed4e9

# The 16 terminal colors

# black
color0 #33364e
color8 #151828

# red
color1 #50f872
color9 #50f872

# green
color2  #4fe88f
color10 #4fe88f

# yellow
color3  #50f7d4
color11 #50f7d4

# blue
color4  #829dd4
color12 #829dd4

# magenta
color5  #cddbf4
color13 #cddbf4

# cyan
color6  #7cf8f7
color14 #7cf8f7

# white
color7  #b5c5db
color15 #ddf7ff
